### PR TITLE
Added post installation support for Fake Ethernet

### PR DESCRIPTION
**Pull request by keysun11952**

### CODE REVIEW

**Comment by intel0753** [comment]
如果你需要什么功能的话，你可以自行Git并修改。如果你的Commit并不能提供改进，并增添大多数人需要的功能的话，建议你可以自行Fork到你的代码库中。如果需要启用App Store，你可以重置网络，使得无线网卡为eth0。

If some function is in your need, you can git the repo and edit as your wish. Your commit didn't seem to make improvements or add functions for the most, I suggest you could fork it into your own repo. If App Store is your need, you could reset the network preference and the WiFi adapter would be eth0.

**Comment by keysun11952** [comment]
This is for those who do not have a working WiFi adapter. 
There are many people out there who are not willing to replace the WiFi adapter.
For them, this is the only way to get AppStore and SideCar to work.

**Comment by intel0753** [comment]
> This is for those who do not have a working WiFi adapter.
> There are many people out there who are not willing to replace the WiFi adapter.
> For them, this is the only way to get AppStore and SideCar to work.

XPS 15 9560 doesn't have an onboard Ethernet adapter, so you have a WiFi card that isn't functional, I wonder if you don't have a functional external WiFi adapter or a functional external ethernet card, how could App Store and SideCar work? If you managed to have an Internet connection, you'd better make that network adapter as eth0.

**Comment by keysun11952** [comment]
> > This is for those who do not have a working WiFi adapter.
> > There are many people out there who are not willing to replace the WiFi adapter.
> > For them, this is the only way to get AppStore and SideCar to work.
> 
> XPS 15 9560 doesn't have an onboard Ethernet adapter, so you have a WiFi card that isn't functional, I wonder if you don't have a functional external WiFi adapter or a functional external ethernet card, how could App Store and SideCar work? If you managed to have an Internet connection, you'd better make that network adapter as eth0.

You can NEVER set an external WiFi / Ethernet adapter to en0. AppStore and SideCar will NOT work if en0 doesn't exist or doen't carry network connection. For those who don't want to swap out their WiFi adapter, the ONLY way to get AppStore and SideCar to work is to use the fake ethernet driver, even if they are using external adapters.

**Comment by jardenliu** [comment]
@keysun11952 thanks for your contribution

**Comment by keysun11952** [comment]
@jardenliu @intel0753 Thank you for maintaining this brilliant repo! It really helped me a lot.

**Comment by keysun11952** [comment]
@jardenliu @intel0753 Thank you for maintaining this brilliant repo! It really helped me a lot.

**Pull request merged**
